"""TEI P5 export of a collation: the critical apparatus in parallel segmentation (``<app>/<lem>/<rdg wit>``)."""

from __future__ import annotations

from xml.sax.saxutils import escape, quoteattr

from ....protocol.textual_criticism import VariantUnit, Witness
from .align import WitnessText


def apparatus(base: WitnessText, units: list[VariantUnit], witnesses: list[Witness], *, title: str,
              include_structural: bool = False) -> str:
    """A TEI document: the witness list, and the base text with every variant unit as an ``<app>``."""
    wits = "\n".join(f'        <witness xml:id={quoteattr(w.id)}>{escape(w.title)}'
                     + (f" ({escape(w.book_id)})" if w.book_id else "") + "</witness>" for w in witnesses)
    body: list[str] = []
    cursor = 0
    for u in sorted(units, key=lambda x: (x.start, x.end)):
        if u.structural and not include_structural:
            continue
        if u.start < cursor:
            continue
        body.append(escape(base.raw[cursor:u.start]))
        parts = []
        for i, r in enumerate(u.readings):
            sigla = " ".join(f"#{s}" for s in r.witnesses)
            text = escape(next(iter(r.forms.values()), r.text)) if r.forms else escape(r.text)
            tag = "lem" if i == 0 else "rdg"
            parts.append(f'<{tag} wit="{sigla}">{text}</{tag}>' if text else f'<{tag} wit="{sigla}"/>')
        if u.lacunose:
            parts.append('<rdg wit="{}" type="lacuna"/>'.format(" ".join(f"#{s}" for s in u.lacunose)))
        body.append(f'<app xml:id={quoteattr(u.id)}>' + "".join(parts) + "</app>")
        cursor = u.end
    body.append(escape(base.raw[cursor:]))
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt><title>{escape(title)}</title></titleStmt>
      <publicationStmt><p>Generated by TaoChronos (computational collation; check against the witnesses).</p></publicationStmt>
      <sourceDesc>
        <listWit>
{wits}
        </listWit>
      </sourceDesc>
    </fileDesc>
    <encodingDesc><variantEncoding method="parallel-segmentation" location="internal"/></encodingDesc>
  </teiHeader>
  <text><body><p>{"".join(body)}</p></body></text>
</TEI>
"""


__all__ = ["apparatus"]
